// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.622Z

/* tslint:disable */
/* eslint-disable */
export * from "./backend";
