// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.933Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface LobbiesSetPlayerDisconnectedResponse
 */
export interface LobbiesSetPlayerDisconnectedResponse {}

/**
 * Check if a given object implements the LobbiesSetPlayerDisconnectedResponse interface.
 */
export function instanceOfLobbiesSetPlayerDisconnectedResponse(
	_value: object,
): _value is LobbiesSetPlayerDisconnectedResponse {
	return true;
}

export function LobbiesSetPlayerDisconnectedResponseFromJSON(
	json: any,
): LobbiesSetPlayerDisconnectedResponse {
	return LobbiesSetPlayerDisconnectedResponseFromJSONTyped(json, false);
}

export function LobbiesSetPlayerDisconnectedResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): LobbiesSetPlayerDisconnectedResponse {
	if (json == null) {
		return json;
	}
	return {};
}

export function LobbiesSetPlayerDisconnectedResponseToJSON(
	value?: LobbiesSetPlayerDisconnectedResponse | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
