/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbiesJoinRequest
 */
export interface LobbiesJoinRequest {
    /**
     * 
     * @type {string}
     * @memberof LobbiesJoinRequest
     */
    lobbyId: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof LobbiesJoinRequest
     */
    players: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof LobbiesJoinRequest
     */
    noWait?: boolean;
}

/**
 * Check if a given object implements the LobbiesJoinRequest interface.
 */
export function instanceOfLobbiesJoinRequest(value: object): value is LobbiesJoinRequest {
    if (!('lobbyId' in value) || value['lobbyId'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function LobbiesJoinRequestFromJSON(json: any): LobbiesJoinRequest {
    return LobbiesJoinRequestFromJSONTyped(json, false);
}

export function LobbiesJoinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesJoinRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lobbyId': json['lobbyId'],
        'players': json['players'],
        'noWait': json['noWait'] == null ? undefined : json['noWait'],
    };
}

export function LobbiesJoinRequestToJSON(value?: LobbiesJoinRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lobbyId': value['lobbyId'],
        'players': value['players'],
        'noWait': value['noWait'],
    };
}

