// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.900Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface LobbiesDestroyResponse
 */
export interface LobbiesDestroyResponse {}

/**
 * Check if a given object implements the LobbiesDestroyResponse interface.
 */
export function instanceOfLobbiesDestroyResponse(
	_value: object,
): _value is LobbiesDestroyResponse {
	return true;
}

export function LobbiesDestroyResponseFromJSON(
	json: any,
): LobbiesDestroyResponse {
	return LobbiesDestroyResponseFromJSONTyped(json, false);
}

export function LobbiesDestroyResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): LobbiesDestroyResponse {
	if (json == null) {
		return json;
	}
	return {};
}

export function LobbiesDestroyResponseToJSON(
	value?: LobbiesDestroyResponse | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
