// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.981Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface LobbiesListRegionsResponse
 */
export interface LobbiesListRegionsResponse {}

/**
 * Check if a given object implements the LobbiesListRegionsResponse interface.
 */
export function instanceOfLobbiesListRegionsResponse(
	_value: object,
): _value is LobbiesListRegionsResponse {
	return true;
}

export function LobbiesListRegionsResponseFromJSON(
	json: any,
): LobbiesListRegionsResponse {
	return LobbiesListRegionsResponseFromJSONTyped(json, false);
}

export function LobbiesListRegionsResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): LobbiesListRegionsResponse {
	if (json == null) {
		return json;
	}
	return {};
}

export function LobbiesListRegionsResponseToJSON(
	value?: LobbiesListRegionsResponse | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
