/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbiesCreateRequest
 */
export interface LobbiesCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof LobbiesCreateRequest
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof LobbiesCreateRequest
     */
    region: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LobbiesCreateRequest
     */
    tags?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof LobbiesCreateRequest
     */
    maxPlayers: number;
    /**
     * 
     * @type {number}
     * @memberof LobbiesCreateRequest
     */
    maxPlayersDirect: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof LobbiesCreateRequest
     */
    players: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof LobbiesCreateRequest
     */
    noWait?: boolean;
}

/**
 * Check if a given object implements the LobbiesCreateRequest interface.
 */
export function instanceOfLobbiesCreateRequest(value: object): value is LobbiesCreateRequest {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('maxPlayers' in value) || value['maxPlayers'] === undefined) return false;
    if (!('maxPlayersDirect' in value) || value['maxPlayersDirect'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function LobbiesCreateRequestFromJSON(json: any): LobbiesCreateRequest {
    return LobbiesCreateRequestFromJSONTyped(json, false);
}

export function LobbiesCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'region': json['region'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'maxPlayers': json['maxPlayers'],
        'maxPlayersDirect': json['maxPlayersDirect'],
        'players': json['players'],
        'noWait': json['noWait'] == null ? undefined : json['noWait'],
    };
}

export function LobbiesCreateRequestToJSON(value?: LobbiesCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'region': value['region'],
        'tags': value['tags'],
        'maxPlayers': value['maxPlayers'],
        'maxPlayersDirect': value['maxPlayersDirect'],
        'players': value['players'],
        'noWait': value['noWait'],
    };
}

