// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.970Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface LobbiesListRegionsRequest
 */
export interface LobbiesListRegionsRequest {}

/**
 * Check if a given object implements the LobbiesListRegionsRequest interface.
 */
export function instanceOfLobbiesListRegionsRequest(
	_value: object,
): _value is LobbiesListRegionsRequest {
	return true;
}

export function LobbiesListRegionsRequestFromJSON(
	json: any,
): LobbiesListRegionsRequest {
	return LobbiesListRegionsRequestFromJSONTyped(json, false);
}

export function LobbiesListRegionsRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): LobbiesListRegionsRequest {
	if (json == null) {
		return json;
	}
	return {};
}

export function LobbiesListRegionsRequestToJSON(
	value?: LobbiesListRegionsRequest | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
