// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.946Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface LobbiesForceGcRequest
 */
export interface LobbiesForceGcRequest {}

/**
 * Check if a given object implements the LobbiesForceGcRequest interface.
 */
export function instanceOfLobbiesForceGcRequest(
	_value: object,
): _value is LobbiesForceGcRequest {
	return true;
}

export function LobbiesForceGcRequestFromJSON(
	json: any,
): LobbiesForceGcRequest {
	return LobbiesForceGcRequestFromJSONTyped(json, false);
}

export function LobbiesForceGcRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): LobbiesForceGcRequest {
	if (json == null) {
		return json;
	}
	return {};
}

export function LobbiesForceGcRequestToJSON(
	value?: LobbiesForceGcRequest | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
