/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbiesListRequest
 */
export interface LobbiesListRequest {
    /**
     * 
     * @type {string}
     * @memberof LobbiesListRequest
     */
    version: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LobbiesListRequest
     */
    regions?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LobbiesListRequest
     */
    tags?: { [key: string]: string; };
}

/**
 * Check if a given object implements the LobbiesListRequest interface.
 */
export function instanceOfLobbiesListRequest(value: object): value is LobbiesListRequest {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function LobbiesListRequestFromJSON(json: any): LobbiesListRequest {
    return LobbiesListRequestFromJSONTyped(json, false);
}

export function LobbiesListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'regions': json['regions'] == null ? undefined : json['regions'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function LobbiesListRequestToJSON(value?: LobbiesListRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'regions': value['regions'],
        'tags': value['tags'],
    };
}

