/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue } from './LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue';
import {
    LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueFromJSON,
    LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueFromJSONTyped,
    LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueToJSON,
} from './LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue';

/**
 * 
 * @export
 * @interface LobbiesCreateResponseLobbyBackendLocalDevelopment
 */
export interface LobbiesCreateResponseLobbyBackendLocalDevelopment {
    /**
     * 
     * @type {object}
     * @memberof LobbiesCreateResponseLobbyBackendLocalDevelopment
     */
    ports: object;
}

/**
 * Check if a given object implements the LobbiesCreateResponseLobbyBackendLocalDevelopment interface.
 */
export function instanceOfLobbiesCreateResponseLobbyBackendLocalDevelopment(value: object): value is LobbiesCreateResponseLobbyBackendLocalDevelopment {
    if (!('ports' in value) || value['ports'] === undefined) return false;
    return true;
}

export function LobbiesCreateResponseLobbyBackendLocalDevelopmentFromJSON(json: any): LobbiesCreateResponseLobbyBackendLocalDevelopment {
    return LobbiesCreateResponseLobbyBackendLocalDevelopmentFromJSONTyped(json, false);
}

export function LobbiesCreateResponseLobbyBackendLocalDevelopmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesCreateResponseLobbyBackendLocalDevelopment {
    if (json == null) {
        return json;
    }
    return {
        
        'ports': json['ports'],
    };
}

export function LobbiesCreateResponseLobbyBackendLocalDevelopmentToJSON(value?: LobbiesCreateResponseLobbyBackendLocalDevelopment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ports': value['ports'],
    };
}

