/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue
 */
export interface LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue {
    /**
     * 
     * @type {string}
     * @memberof LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue
     */
    protocol: LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueProtocolEnum;
    /**
     * 
     * @type {string}
     * @memberof LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue
     */
    hostname: string;
    /**
     * 
     * @type {number}
     * @memberof LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue
     */
    port: number;
}


/**
 * @export
 */
export const LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueProtocolEnum = {
    Http: 'http',
    Tcp: 'tcp',
    Udp: 'udp'
} as const;
export type LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueProtocolEnum = typeof LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueProtocolEnum[keyof typeof LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueProtocolEnum];


/**
 * Check if a given object implements the LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue interface.
 */
export function instanceOfLobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue(value: object): value is LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue {
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueFromJSON(json: any): LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue {
    return LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueFromJSONTyped(json, false);
}

export function LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue {
    if (json == null) {
        return json;
    }
    return {
        
        'protocol': json['protocol'],
        'hostname': json['hostname'],
        'port': json['port'],
    };
}

export function LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValueToJSON(value?: LobbiesCreateResponseLobbyBackendLocalDevelopmentPortsValue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'protocol': value['protocol'],
        'hostname': value['hostname'],
        'port': value['port'],
    };
}

