/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbiesFindOrCreateRequestCreateConfig
 */
export interface LobbiesFindOrCreateRequestCreateConfig {
    /**
     * 
     * @type {string}
     * @memberof LobbiesFindOrCreateRequestCreateConfig
     */
    region: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LobbiesFindOrCreateRequestCreateConfig
     */
    tags?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof LobbiesFindOrCreateRequestCreateConfig
     */
    maxPlayers: number;
    /**
     * 
     * @type {number}
     * @memberof LobbiesFindOrCreateRequestCreateConfig
     */
    maxPlayersDirect: number;
}

/**
 * Check if a given object implements the LobbiesFindOrCreateRequestCreateConfig interface.
 */
export function instanceOfLobbiesFindOrCreateRequestCreateConfig(value: object): value is LobbiesFindOrCreateRequestCreateConfig {
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('maxPlayers' in value) || value['maxPlayers'] === undefined) return false;
    if (!('maxPlayersDirect' in value) || value['maxPlayersDirect'] === undefined) return false;
    return true;
}

export function LobbiesFindOrCreateRequestCreateConfigFromJSON(json: any): LobbiesFindOrCreateRequestCreateConfig {
    return LobbiesFindOrCreateRequestCreateConfigFromJSONTyped(json, false);
}

export function LobbiesFindOrCreateRequestCreateConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesFindOrCreateRequestCreateConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'region': json['region'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'maxPlayers': json['maxPlayers'],
        'maxPlayersDirect': json['maxPlayersDirect'],
    };
}

export function LobbiesFindOrCreateRequestCreateConfigToJSON(value?: LobbiesFindOrCreateRequestCreateConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'region': value['region'],
        'tags': value['tags'],
        'maxPlayers': value['maxPlayers'],
        'maxPlayersDirect': value['maxPlayersDirect'],
    };
}

