/* tslint:disable */
/* eslint-disable */
/**
 * Open Game Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbiesSetPlayerDisconnectedRequest
 */
export interface LobbiesSetPlayerDisconnectedRequest {
    /**
     * 
     * @type {string}
     * @memberof LobbiesSetPlayerDisconnectedRequest
     */
    lobbyId?: string;
    /**
     * 
     * @type {string}
     * @memberof LobbiesSetPlayerDisconnectedRequest
     */
    lobbyToken?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LobbiesSetPlayerDisconnectedRequest
     */
    playerTokens: Array<string>;
}

/**
 * Check if a given object implements the LobbiesSetPlayerDisconnectedRequest interface.
 */
export function instanceOfLobbiesSetPlayerDisconnectedRequest(value: object): value is LobbiesSetPlayerDisconnectedRequest {
    if (!('playerTokens' in value) || value['playerTokens'] === undefined) return false;
    return true;
}

export function LobbiesSetPlayerDisconnectedRequestFromJSON(json: any): LobbiesSetPlayerDisconnectedRequest {
    return LobbiesSetPlayerDisconnectedRequestFromJSONTyped(json, false);
}

export function LobbiesSetPlayerDisconnectedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesSetPlayerDisconnectedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lobbyId': json['lobbyId'] == null ? undefined : json['lobbyId'],
        'lobbyToken': json['lobbyToken'] == null ? undefined : json['lobbyToken'],
        'playerTokens': json['playerTokens'],
    };
}

export function LobbiesSetPlayerDisconnectedRequestToJSON(value?: LobbiesSetPlayerDisconnectedRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lobbyId': value['lobbyId'],
        'lobbyToken': value['lobbyToken'],
        'playerTokens': value['playerTokens'],
    };
}

