// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.656Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface RateLimitThrottleResponse
 */
export interface RateLimitThrottleResponse {}

/**
 * Check if a given object implements the RateLimitThrottleResponse interface.
 */
export function instanceOfRateLimitThrottleResponse(
	_value: object,
): _value is RateLimitThrottleResponse {
	return true;
}

export function RateLimitThrottleResponseFromJSON(
	json: any,
): RateLimitThrottleResponse {
	return RateLimitThrottleResponseFromJSONTyped(json, false);
}

export function RateLimitThrottleResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RateLimitThrottleResponse {
	if (json == null) {
		return json;
	}
	return {};
}

export function RateLimitThrottleResponseToJSON(
	value?: RateLimitThrottleResponse | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
