// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:59.047Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface RivetCallResponse
 */
export interface RivetCallResponse {}

/**
 * Check if a given object implements the RivetCallResponse interface.
 */
export function instanceOfRivetCallResponse(
	_value: object,
): _value is RivetCallResponse {
	return true;
}

export function RivetCallResponseFromJSON(json: any): RivetCallResponse {
	return RivetCallResponseFromJSONTyped(json, false);
}

export function RivetCallResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RivetCallResponse {
	if (json == null) {
		return json;
	}
	return {};
}

export function RivetCallResponseToJSON(value?: RivetCallResponse | null): any {
	if (value == null) {
		return value;
	}
	return {};
}
