// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.874Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface TokensExtendResponse
 */
export interface TokensExtendResponse {}

/**
 * Check if a given object implements the TokensExtendResponse interface.
 */
export function instanceOfTokensExtendResponse(
	_value: object,
): _value is TokensExtendResponse {
	return true;
}

export function TokensExtendResponseFromJSON(json: any): TokensExtendResponse {
	return TokensExtendResponseFromJSONTyped(json, false);
}

export function TokensExtendResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): TokensExtendResponse {
	if (json == null) {
		return json;
	}
	return {};
}

export function TokensExtendResponseToJSON(
	value?: TokensExtendResponse | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
