// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.839Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface TokensValidateRequest
 */
export interface TokensValidateRequest {}

/**
 * Check if a given object implements the TokensValidateRequest interface.
 */
export function instanceOfTokensValidateRequest(
	_value: object,
): _value is TokensValidateRequest {
	return true;
}

export function TokensValidateRequestFromJSON(
	json: any,
): TokensValidateRequest {
	return TokensValidateRequestFromJSONTyped(json, false);
}

export function TokensValidateRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): TokensValidateRequest {
	if (json == null) {
		return json;
	}
	return {};
}

export function TokensValidateRequestToJSON(
	value?: TokensValidateRequest | null,
): any {
	if (value == null) {
		return value;
	}
	return {};
}
