// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:58.701Z

import * as runtime from "../../runtime";

import type {
	RateLimitThrottleRequest,
	RateLimitThrottleResponse,
} from "../../models/index";
import {
	RateLimitThrottleRequestToJSON,
	RateLimitThrottleResponseFromJSON,
} from "../../models/index";

import type {
	RateLimitThrottlePublicRequest,
	RateLimitThrottlePublicResponse,
} from "../../models/index";
import {
	RateLimitThrottlePublicRequestToJSON,
	RateLimitThrottlePublicResponseFromJSON,
} from "../../models/index";

export class RateLimit extends runtime.BaseAPI {
	public async throttle(
		request: RateLimitThrottleRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<RateLimitThrottleResponse> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};
		headerParameters["Content-Type"] = "application/json";

		const response = await this.request({
			path: `/modules/rate_limit/scripts/throttle/call`,
			method: "POST",
			headers: headerParameters,
			query: queryParameters,
			body: RateLimitThrottleRequestToJSON(request),
		}, initOverrides);

		return RateLimitThrottleResponseFromJSON(await response.json());
	}

	public async throttlePublic(
		request: RateLimitThrottlePublicRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<RateLimitThrottlePublicResponse> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};
		headerParameters["Content-Type"] = "application/json";

		const response = await this.request({
			path: `/modules/rate_limit/scripts/throttle_public/call`,
			method: "POST",
			headers: headerParameters,
			query: queryParameters,
			body: RateLimitThrottlePublicRequestToJSON(request),
		}, initOverrides);

		return RateLimitThrottlePublicResponseFromJSON(await response.json());
	}
}
