// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-08-15T23:48:59.082Z

import * as runtime from "../../runtime";

import type { RivetCallRequest, RivetCallResponse } from "../../models/index";
import {
	RivetCallRequestToJSON,
	RivetCallResponseFromJSON,
} from "../../models/index";

import type {
	RivetGetConfigRequest,
	RivetGetConfigResponse,
} from "../../models/index";
import {
	RivetGetConfigRequestToJSON,
	RivetGetConfigResponseFromJSON,
} from "../../models/index";

export class Rivet extends runtime.BaseAPI {
	public async call(
		request: RivetCallRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<RivetCallResponse> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};
		headerParameters["Content-Type"] = "application/json";

		const response = await this.request({
			path: `/modules/rivet/scripts/call/call`,
			method: "POST",
			headers: headerParameters,
			query: queryParameters,
			body: RivetCallRequestToJSON(request),
		}, initOverrides);

		return RivetCallResponseFromJSON(await response.json());
	}

	public async getConfig(
		request: RivetGetConfigRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<RivetGetConfigResponse> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};
		headerParameters["Content-Type"] = "application/json";

		const response = await this.request({
			path: `/modules/rivet/scripts/get_config/call`,
			method: "POST",
			headers: headerParameters,
			query: queryParameters,
			body: RivetGetConfigRequestToJSON(request),
		}, initOverrides);

		return RivetGetConfigResponseFromJSON(await response.json());
	}
}
