import * as tjs from "typescript-json-schema";
import path from 'path';
import { promises as fs } from 'fs';
import { Registry } from "./registry";

export async function generateEntrypoint(registry: Registry, schema: tjs.Definition) {
    let outDir = path.join(registry.path, 'dist');
    let outPath = path.join(outDir, 'entrypoint.ts');

    // Generate module configs
    let modImports = "";
    let modConfig = "{";
    for (let modName in registry.modules) {
        let mod = registry.modules[modName];

        modConfig += `${JSON.stringify(modName)}: {`;

        // Generate script configs
        modConfig += "scripts: {";
        for (let scriptName in mod.scripts) {
            let handlerIdent = `modules__${modName}__${scriptName}__handler`;

            let scriptPath = path.relative(outDir, path.join(mod.path, 'scripts', scriptName));
            scriptPath = scriptPath.endsWith(".ts") ? scriptPath.slice(0, -3) : scriptPath;

            modImports = `import { handler as ${handlerIdent} } from '${scriptPath}';\n`;
            modConfig += `${JSON.stringify(scriptName)}: { handler: ${handlerIdent} },`;
        }
        modConfig += "},";

        modConfig += "}";
    }
    modConfig += "}";

    // Generate source
    let source = `
// This file is generated by @ogs/engine-builder

import { Runtime } from "${path.relative(outDir, path.resolve(__dirname, '..', '..', 'runtime', 'src'))}/index";

${modImports}

async function main() {
    let runtime = new Runtime({
        modules: ${modConfig},
        schema: ${JSON.stringify(schema)},
    });
    let response = await runtime.call('users', 'get', { userIds: ['abc', 'def'] });
    console.log('Call response', response);
    // await runtime.run();
}

main();

`;

    // Write file
    console.log('Writing entrypoint', outPath);
    await fs.writeFile(outPath, source, 'utf8');
}

